### PR TITLE
Rename JavascriptServiceProvider.php to JavaScriptServiceProvider.php

### PR DESCRIPTION
**Pull request by Stayallive**
This causes all kinds of problems on Linux boxes :)

### CODE REVIEW

**Comment by dominicmartineau** [comment]
:+1:

**Comment by Rn2ee** [comment]
+1

**Comment by nWidart** [comment]
Can the please be merged ? This causes issues on linux.

**Comment by nWidart** [comment]
@Stayallive Since Jeffrey won't merge this anytime soon, could you please update your fork ? I see it's 12 commits behind. So that I can use your version. :smiley: Thanks!

**Comment by Stayallive** [comment]
@nWidart Done!

**Comment by Stayallive** [comment]
I just however now use the lowercase name for the service provider after it broke my deployment once again when migrating to a new server :( So thats also a solution.

**Comment by nWidart** [comment]
Awesome, thanks!
Oh really so using the official package, but with `J'Laracasts\Utilities\JavaScript\JavascriptServiceProvider',` ?

**Comment by Stayallive** [comment]
Jep :)

**Comment by nWidart** [comment]
Cool, good to know :+1:

**Comment by philbates35** [comment]
+1 This had me scratching my head for a while on my Linux machine.

As stated above, registering `Laracasts\Utilities\JavaScript\JavascriptServiceProvider::class` does not work, but `'Laracasts\Utilities\JavaScript\JavascriptServiceProvider'` as a workaround does work.

**Comment by bradbird1990** [comment]
This fix did not work for me using multiple combinations of fixes even when using version 2.0. It was breaking my Envoyer.io push deployment (I previously used another version until recently when this issue was still a problem), but it was because I was using the provider in a string with the lowercase "Javascript" instead of camel-case "JavaScript" so if anyone is stuck be sure to use the following implementation.

```'Laracasts\Utilities\JavaScript\JavaScriptServiceProvider',```

In a string... With camel-case "JavaScript" and it will work fine.

**Pull request merged**
